services:

  eureka:
    build: ./medilabo-eureka-server
    container_name: eureka
    ports:
      - "8761:8761"

  gateway:
    build: ./medilabo-gateway
    container_name: gateway
    ports:
      - "8081:8081"
    depends_on:
      - eureka

  patient:
    build: ./medilabo-patient-service
    container_name: patient
    ports:
      - "9001:9001"
    depends_on:
      - eureka

  notes:
    build: ./medilabo-note
    container_name: notes
    ports:
      - "8082:8082"
    depends_on:
      - eureka

  risk:
    build: ./medilabo-risk-diabetes-service
    container_name: risk
    ports:
      - "8083:8083"
    depends_on:
      - eureka

  patient-ui:
    build: ./medilabo-patientui
    container_name: patient-ui
    ports:
      - "8080:8080"
    depends_on:
      - gateway
      - patient
      - notes
      - risk

  mysql-patient:
    image: mysql:8.0
    container_name: mysql-patient
    environment:
      MYSQL_DATABASE: patientservice
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-patient-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  mongodb-note:
    image: mongo:6.0
    container_name: mongodb-note
    environment:
      MONGO_INITDB_DATABASE: medilaboSolution
    ports:
      - "27018:27017"
    volumes:
      - mongodb-note-data:/data/db

volumes:
  mysql-patient-data:
  mongodb-note-data:
